### ISSUE TITLE
Admin role

### ISSUE THREAD

**Issue by kkm1991** [tdh-imam/App#6]
admin account ကနေ user တွေကို edit လုပ်ရင် ရှိပြီးသား role တွေ supervisior တွေ မပေါ်ဘူး ပြည့်တော့ ward/villages တွေကိုပြောင်းလို.မရဘူး
![issue](https://github.com/tdh-imam/App/assets/101306893/cf30ca33-5928-483a-ad9b-443b0412806c)

**Comment by aungkyawminn** [comment]
@kkm1991  ရှင်းပြီးပြီ ပြန်စမ်းကြည့် ရရင် issue ကို Close လိုက်

**Comment by kkm1991** [comment]
hard reload လုပ်ထား တာလဲ role နဲ့ supervisior မှာလာမပြသေးဘူး ကိုကြီးပြန်စစ်ကြည့်ပေးပါဦး 
![Uploading hard reload.gif…]()

**Comment by aungkyawminn** [comment]
![image](https://github.com/tdh-imam/App/assets/11250072/3c512671-584d-4861-8fd0-350fa6e3e234)

**Comment by aungkyawminn** [comment]
upload ကပုံမပါလာဘူး။ server မှာခုကြည့်တာတော့ Role ရော supervisor ရောရှိတယ်
